### PR TITLE
support primitive shapes while loading urdfs

### PR DESCRIPTION
**Pull request by zcczhang**

### CODE REVIEW

**Comment by natevm** [comment]
Just glancing at the code atm, why not use the built in NVISII box mesh rather than importing a box obj? I tend to prefer we use the built in primitives that come with NVISII rather than sourcing them from an external OBJ

**Comment by zcczhang** [comment]
> 
The code I used below for NVISII box mesh will somewhat create the box with incorrect dimensions. Other primitives work fine but maybe I'm missing something in loading the NVISII box mesh?
 
```python
nv_objects[object_name] = nv.entity.create(
    name=object_name,
    mesh=nv.mesh.create_box(
         name=object_name,
         size=nv.vec3(dimensions[0], dimensions[1], dimensions[2])
    ),
    transform=nv.transform.create(object_name),
    material=nv.material.create(object_name),
)
```

**Comment by natevm** [comment]
Ok, looking better. 

Could you explain what the pybullet_data package does? I’m unfamiliar with that. 

Otherwise looks good to me

**Comment by zcczhang** [comment]
sure, this is just for using to get the local path of the pybullet data (local folder same as [here](https://github.com/bulletphysics/bullet3/tree/master/examples/pybullet/gym/pybullet_data)). In this way, it just doesn't need to download mesh files again once the pybullet has already been installed.

**Comment by natevm** [comment]
Thanks for contributing! 🙂

**Pull request merged**
